language: python
python:
  - "3.6"
install:
  - pip install python-coveralls
  - pip install -e ."[snips,test]"
  - snips-nlu download en
script:
  - python -m nose --with-doctest --with-coverage --cover-package=pytlas
after_success:
  - coveralls
