language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install codecov pylint nosexcover
  - pip install -e ."[snips,test]"
  - pip uninstall -y pytest
  - snips-nlu download en
script:
  - pylint setup.py pytlas
  - python -m nose --with-doctest --with-xcoverage --cover-package=pytlas
after_success:
  - codecov
